### ISSUE TITLE
error message needing help

### ISSUE THREAD

**Issue by elffairy90** [clara-parabricks/AtacWorks#244]
Hi, 

Could I run my code like this? Do you see any problems? I mean for the weights_path, could it be my own big.wig of a clean sample? But, when I ran this, i ran into this following problem. I'm new to dry lab, I would really appreciate your help! Thank you!

atacworks denoise \
    --noisybw /data/jwang/files_atacworks/test/control_R1.mLb.clN.bigWig \
    --genome /data/jwang/AtacWorks/data/reference/mm10.auto.sizes \
    --weights_path /data/jwang/files_atacworks/training/atacworks/control_R1.mLb.clN.bigWig \
    --out_home "./" \
    --exp_name "atacworks_denoise" \
    --distributed \
    --num_workers 0

INFO:2021-07-18 10:57:51,501:AtacWorks-intervals] Generating intervals tiling across all chromosomes             in sizes file: /data/jwang/AtacWorks/data/reference/mm10.auto.sizes
INFO:2021-07-18 10:57:51,598:AtacWorks-intervals] Done!
Traceback (most recent call last):
  File "/usr/local/share/virtualenvs/env37/bin/atacworks", line 8, in <module>
    sys.exit(main())
  File "/usr/local/share/virtualenvs/env37/lib/python3.7/site-packages/scripts/main.py", line 487, in main
    extension=".bw")
  File "/usr/local/share/virtualenvs/env37/lib/python3.7/site-packages/atacworks/dl4atac/utils.py", line 235, in gather_files_from_cmdline
    assert path.endswith(extension)
AssertionError

**Comment by avantikalal** [comment]
HI @elffairy90. --weights_path should be not a bigwig file but the path to a trained AtacWorks model. You can either train a model yourself using clean and noisy bigwig files (see tutorial 1) or else download one of our trained models. We recommend training a model if you have data available.
